Character's skills
Internship2017/star_wars_ffg pull request #31
Opened 2017-06-21 19:30 UTC by Anapaotrev

### What does this PR do ?
* Creates the skills model
* Adds the skills to the character
![bitmoji](https://render.bitstrips.com/v2/cpanel/8263858-188977818_10-s4-v1.png?transparent=1&palette=1&width=246)

2017-06-21 19:34 UTC, kurenn requested changes

2017-06-21 19:34 UTC, kurenn commented on app/models/skill.rb
> +  def parse_skills
This should be a class method...

2017-06-21 19:34 UTC, kurenn commented on app/models/character.rb
> +  	Skill.new.parse_skills.each do |skill|
So you need to instantiate a skill to create other skills?

2017-06-21 19:34 UTC, kurenn commented on spec/models/character_spec.rb
> +RSpec.describe Character, type: :model do
There are tests missing for validations

2017-06-21 19:34 UTC, kurenn commented on spec/models/skill_spec.rb
> +RSpec.describe Skill, type: :model do
A good test to add would be the `parse_skills` method

2017-06-21 20:31 UTC, kurenn requested changes

2017-06-21 20:31 UTC, kurenn commented on spec/models/skill_spec.rb
> +describe "Skill" do
Why is this outside the Skill block?

2017-06-21 20:31 UTC, kurenn commented on spec/models/skill_spec.rb
> +			file = File.read("#{Rails.root}/lib/data/Skills.json")
![shits-on-fire-yo_o_153652](https://user-images.githubusercontent.com/236312/27405268-85442284-5696-11e7-9ade-3db4cef0fd1c.jpg)

2017-06-21 20:31 UTC, kurenn commented on spec/models/skill_spec.rb
> +		  	hash_of_skills = data_hash["Skills"]["Skill"]
This test is too valid as you are using the actual implementation to test the output of the test...

2017-06-21 20:31 UTC, kurenn commented on spec/models/character_spec.rb
>    it { should validate_presence_of(:campaign) }
Are you missing a skills has  many test?

2017-06-21 20:44 UTC, Anapaotrev commented on spec/models/skill_spec.rb
> +			file = File.read("#{Rails.root}/lib/data/Skills.json")
![bitmoji](https://render.bitstrips.com/v2/cpanel/9665646-188977818_11-s4-v1.png?transparent=1&palette=1&width=246)

2017-06-21 21:06 UTC, kurenn requested changes

2017-06-21 21:06 UTC, kurenn commented on spec/models/skill_spec.rb
> +	describe "Skill" do
Another `describe "Skill"` isn't up there?

2017-06-22 16:11 UTC, kurenn approved these changes

2017-06-22 16:11 UTC, kurenn commented on app/services/json_skill.rb
> +class JsonSkill
![9b62f01e-3953-11e7-80f8-797f7f08a43e](https://user-images.githubusercontent.com/236312/27444275-71ac5160-573b-11e7-8a07-065172340269.jpg)

2017-06-22 16:11 UTC, Anapaotrev commented on app/services/json_skill.rb
> +class JsonSkill
![bitmoji](https://render.bitstrips.com/v2/cpanel/9990876-188977818_11-s4-v1.png?transparent=1&palette=1&width=246)

2017-06-22 16:15 UTC, merged