Adding style to sign in form
Internship2017/star_wars_ffg pull request #5
Opened 2017-06-19 21:52 UTC by Anapaotrev

### What does this PR do?

* Styling the sign in form with bootstrap !

![bitmoji](https://render.bitstrips.com/v2/cpanel/10149736-188977818_10-s4-v1.png?transparent=1&palette=1&width=246)

2017-06-19 22:06 UTC, kurenn requested changes

2017-06-19 22:06 UTC, kurenn commented on app/assets/stylesheets/signin_form.scss
> +@import "bootstrap";
Why are you importing bootstrap in here? isn't already on the `application.scss` file?

2017-06-19 22:06 UTC, kurenn commented on app/assets/stylesheets/signin_form.scss
> +.border-form-div {
Please order the properties for the css alphabetically

2017-06-19 22:06 UTC, kurenn commented on app/assets/stylesheets/signin_form.scss
> +.border-form-div {
I don't feel quite comfortable with this class name, it contain html element names on the class name...and also a property, so I don't know what it is suppose to do...

2017-06-19 22:06 UTC, kurenn commented on app/views/devise/sessions/new.html.erb
> +<%= stylesheet_link_tag "signin_form" %>
This style guide will be included in the middle of the HTML, that is not quite right, check out the `content_for` method for Rails to include this on the header dinamically

2017-06-19 22:06 UTC, kurenn commented on app/views/devise/sessions/new.html.erb
> +<div class= 'border-form-div'>
On html you don't separate the `=` sign from the value

2017-06-19 22:08 UTC, Anapaotrev commented on app/assets/stylesheets/signin_form.scss
> +@import "bootstrap";
It didn't work we didn't know why, and when we changed it and then it worked.

2017-06-20 00:19 UTC, kurenn requested changes

2017-06-20 00:19 UTC, kurenn commented on app/assets/stylesheets/application.scss
> +.btn-purple {
I would not set the class name to attached to a css property value, what would happen if tomorrow you decide purple is not the right color and change to, let's say orange, you will have to update the class name in order for the button to make sense at all....

2017-06-20 00:19 UTC, kurenn commented on app/views/devise/sessions/new.html.erb
> +<%= stylesheet_link_tag "signin_form" %>
Are we checking this?

2017-06-20 00:19 UTC, kurenn commented on app/assets/stylesheets/signin_form.scss
> +@import "bootstrap";
So?

2017-06-20 15:57 UTC, kurenn commented
![norris](https://user-images.githubusercontent.com/236312/27343014-4e3e5254-55a7-11e7-8c2a-314867c88da3.jpg)

2017-06-20 16:00 UTC, kurenn requested changes

2017-06-20 16:00 UTC, kurenn commented on app/assets/stylesheets/signin_form.scss
> +  background-color: #fff;
Please update this to be upcased, I can see you are using upcased color values...

2017-06-20 16:00 UTC, kurenn commented on app/assets/stylesheets/signin_form.scss
> +  background-color: #fff;
Please update this to be upcased, I can see you are using upcased color values...

2017-06-20 16:00 UTC, kurenn commented on app/assets/stylesheets/signin_form.scss
> +  border: 1px solid #e5e5e5 ;
Please update this to be upcased, I can see you are using upcased color values...

2017-06-20 16:05 UTC, kurenn requested changes

2017-06-20 16:05 UTC, kurenn commented on app/assets/stylesheets/signin_form.scss
> +  border: 1px solid #E5E5E5 ;
Remove the space between the color and the `;`

2017-06-20 16:10 UTC, kurenn approved these changes

2017-06-20 16:11 UTC, merged