Adds home page and fixes style of campaign button
Internship2017/star_wars_ffg pull request #60
Opened 2017-06-27 22:04 UTC by erik0686

### What does this PR do?

* fixes style of campaign index view to match others
* adds home view

2017-06-28 19:32 UTC, kurenn requested changes

2017-06-28 19:32 UTC, kurenn commented on app/assets/stylesheets/campaigns.scss
> +.space_between_image {
You were using dash case and suddenly decided to go with snake case?

2017-06-28 19:32 UTC, kurenn commented on app/assets/stylesheets/home.scss
> +    color: black;
Never use named colors, instead, use hex values

2017-06-28 19:32 UTC, kurenn commented on app/assets/stylesheets/home.scss
> +    color: #C09448;
Check for indentation

2017-06-28 19:32 UTC, kurenn commented on app/controllers/home_controller.rb
> +
Remove this space

2017-06-28 19:32 UTC, kurenn commented on app/helpers/home_helper.rb
> +module HomeHelper
Remove this empty file

2017-06-29 19:45 UTC, kurenn requested changes

2017-06-29 19:45 UTC, kurenn commented on app/assets/stylesheets/home.scss
> +a:link {
From line 15 to 27, you can use the sass nesting feature, something like:

```sass
a {
 color:  #000;

 &:hover {
   color: #000;
 }
....
}
```

2017-06-29 19:46 UTC, erik0686 commented on app/assets/stylesheets/home.scss
> +a:link {
Ok, I will change it

2017-06-29 19:46 UTC, mayra-cabrera requested changes
@erik0686 Be consistent with your CSS files indentation settings, some of them have four spaces and other ones have two spaces

2017-06-29 20:01 UTC, kurenn commented on app/assets/stylesheets/home.scss
> +  &:hover {
Add a line between the pseudoselectors

2017-06-29 20:07 UTC, kurenn approved these changes

2017-06-29 20:11 UTC, kurenn requested changes

2017-06-29 20:11 UTC, kurenn commented on app/assets/stylesheets/home.scss
> +}
Add a separation in here please

2017-06-29 20:38 UTC, merged